apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client1
  name: client1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client1
  template:
    metadata:
      labels:
        app: client1
    spec:
      containers:
      - image: praqma/oidc-oauth2-katas-client:sha-8a5e157
        name: client
        command: ["npm", "run", "watch"]
        #command: ["node", "src/client.js"]
        env:
        - name: NODE_ENV
          value: "development"
        - name: CLIENT_TITLE
          value: "Confidential Client1-v2"
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: client1
              key: client_id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: client1
              key: client_secret
        - name: CLIENT_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: client1
              key: client_base_url
        - name: SESSION_SECRET
          value: "CloakAndDaggers"
        - name: OIDC_ISSUER_URL
          valueFrom:
            configMapKeyRef:
              name: client1
              key: oidc_issuer_url
        - name: REDIS_URL
          value: ""
        workingDir: /apps/client-nodejs-v2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: client1
  name: client1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: client1
  type: ClusterIP
