apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client2
  name: client2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client2
  template:
    metadata:
      labels:
        app: client2
    spec:
      containers:
      - image: praqma/oidc-oauth2-katas-client:sha-62fa757
        name: client
        command: ["node", "src/client.js"]
        env:
        - name: CLIENT_TITLE
          value: "Confidential Client2"
        - name: CLIENT_STYLEFILE
          value: "style2.css"
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: client2
              key: client_id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: client2
              key: client_secret
        - name: CLIENT_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: client2
              key: client_base_url
        - name: OIDC_AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: client2
              key: oidc_auth_url
        - name: OIDC_TOKEN_URL
          valueFrom:
            configMapKeyRef:
              name: client2
              key: oidc_token_url
        workingDir: /apps/client-nodejs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: client2
  name: client2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: client2
  type: ClusterIP
