fullnameOverride: client1
config:
  existingSecret: client1
  configFile: |-
    provider = "oidc"
    provider_display_name = "OIDC through $OIDC_ISSUER_URL"
    oidc_issuer_url = "$OIDC_ISSUER_URL"
    redirect_url = "$OAUTH2_PROXY_EP/oauth2/callback"
    email_domains = [ "example.com" ]
    upstreams = [ "$OAUTH2_PROXY_UPSTREAM" ]
    cookie_secure = true
    cookie_httponly = true
