config:
  existingSecret: client1
  configFile: |-
    provider = "oidc"
    provider_display_name = "OIDC through $OIDC_ISSUER_URL"
    oidc_issuer_url = "$OIDC_ISSUER_URL"
    redirect_url = "$OAUTH2_PROXY_EP/oauth2/callback"
    email_domains = [ "example.com" ]
    upstreams = [ "http://httpbin:80" ]
    cookie_secure = false
    cookie_httponly = false
