apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: object-store-v2
  name: object-store-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-store-v2
  template:
    metadata:
      labels:
        app: object-store-v2
    spec:
      containers:
      - image: praqma/oidc-oauth2-katas-client:sha-3ecef8f
        name: object-store
        command: ["npm", "run", "watch"]
        #command: ["node", "src/client.js"]
        env:
        - name: NODE_ENV
          value: "development"
        workingDir: /apps/object-store-v2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: object-store-v2
  name: object-store-v2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: object-store-v2
  type: ClusterIP
