apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: praqma/oidc-oauth2-katas-client:0.1.0
        name: api
        command: ["npm", "run", "watch"]
        env:
        - name: OIDC_ISSUER_URL
          valueFrom:
            configMapKeyRef:
              name: api
              key: oidc_issuer_url
        workingDir: /apps/object-store
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5010
  selector:
    app: api
  type: ClusterIP
