apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spa-login
  name: spa-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa-login
  template:
    metadata:
      labels:
        app: spa-login
    spec:
      containers:
      - image: praqma/oidc-oauth2-katas-client:sha-62fa757
        name: client
        command: ["node", "src/index.js"]
        workingDir: /apps/bff
        env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: client1
              key: client_id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: client1
              key: client_secret
        - name: REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              name: spa-login
              key: redirect_url
        - name: OIDC_ISSUER_URL
          valueFrom:
            configMapKeyRef:
              name: spa-login
              key: oidc_issuer_url
        - name: REDIS_URL
          value: redis://session-store
        - name: SESSION_SECRET
          value: ASecretDontTell
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spa-login
  name: spa-login
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5010
  selector:
    app: spa-login
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: session-store
  name: session-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-store
  template:
    metadata:
      labels:
        app: session-store
    spec:
      containers:
      - image: redis:6.2.4-alpine
        name: redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: session-store
  name: session-store
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: session-store
  type: ClusterIP
